logging:
  level:
    root: info
    io.github.syakuis: info
    org.springframework.web: info
server:
  port: 8080
  forward-headers-strategy: native
spring:
  main:
    banner-mode: console
  messages:
    basename: i18n/message
  mvc:
    favicon:
      requestMapping: favicon.ico
  test:
    restdocs-easy:
      uri-scheme: https
      uri-host: github.com
      uri-port: 443