name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@main

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main

      - name: Build with Gradle
        run: >
          ./gradlew
          -Pspring.profiles.active=test
          -PmavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}
          -PmavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }}
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
          -Psigning.signingInMemoryKey=${{ secrets.SIGNING_IN_MEMORY_KEY }}
          build publish